// Copyright 2018 The go-bindata Authors. All rights reserved.
// Use of this source code is governed by a CC0 1.0 Universal (CC0 1.0)
// Public Domain Dedication license that can be found in the LICENSE file.

package bindata

const (
	headerGeneratedBy = "// Code generated by go-bindata. DO NOT EDIT.\n"
)
